# Generated by Django 3.0.5 on 2020-05-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jvacancy', '0004_auto_20200525_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
